version: '3'

services:
  app_tests:
    build: .
    image: cese/poc-esp32-integracion-test
    volumes:
      - .:/project
    command: ceedling

  app:
    build: .
    image: cese/poc-esp32-integracion-app
    depends_on: 
      - app_tests
    volumes:
      - .:/project
    command: idf.py build
  