steps:

  - name: 'gcr.io/cloud-builders/docker-compose'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cd pocs/esp32-integracion && docker-compose up'

  # Opcional: Subir las imágenes a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:$BUILD_ID']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/$IMAGE_NAME:$BUILD_ID'

# substitutions:
#   PROJECT_ID: "cese-robot"
#   _IMAGE_NAME: "my-image"
#   _SERVICE_ACCOUNT: "my-service-account"