steps:

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cd pocs/esp32-integracion && docker-compose up'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - '${_IMAGE_NAME}'
      - 'gcr.io/cese-robot/${_IMAGE_NAME}:$BUILD_ID'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID']
    waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
  failure: FAIL_FAST

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'

substitutions:
#   PROJECT_ID: "cese-robot"
  _IMAGE_NAME: "cese/poc-esp32-integracion-test"
#   _SERVICE_ACCOUNT: "my-service-account"