steps:


  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd pocs/esp32-integracion
        docker-compose build --no-cache --verbose
        docker-compose up --abort-on-container-exit --exit-code-from app_tests --verbose

  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - 'cd pocs/esp32-integracion && docker-compose build --abort-on-container-exit --exit-code-from app_tests'

  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - 'docker images'


options:
  logging: CLOUD_LOGGING_ONLY


substitutions:
  _IMAGE_NAME: "cese/poc-esp32-integracion"