version: '3'

services:
  # app_tests:
  #   build: .
  #   volumes:
  #     - .:/project
  #   command: ceedling

  app:
    build: .
    # depends_on: 
    #   - app_tests
    image: cese/esp32-motor
    volumes:
      - .:/project
    command: idf.py clean build
  